/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Card: (typeof import('./../components/Dashboard/Card.vue'))['default']
    CardItem: (typeof import('./../components/Dashboard/CardItem.vue'))['default']
    ChartTitle: (typeof import('./../components/Dashboard/ChartTitle.vue'))['default']
    Header: (typeof import('./../components/Layout/Header.vue'))['default']
    Layout: (typeof import('./../components/Layout/index.vue'))['default']
    LineChart: (typeof import('./../components/Dashboard/LineChart.vue'))['default']
    Nav: (typeof import('./../components/Layout/Nav.vue'))['default']
    PieChart: (typeof import('./../components/Dashboard/PieChart.vue'))['default']
    RaddarChart: (typeof import('./../components/Dashboard/RaddarChart.vue'))['default']
    TopSwiper: (typeof import('./../components/Dashboard/TopSwiper.vue'))['default']
  }
}
