/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Header: (typeof import('./../components/Layout/Header.vue'))['default']
    Layout: (typeof import('./../components/Layout/index.vue'))['default']
    Nav: (typeof import('./../components/Layout/Nav.vue'))['default']
  }
}
